### PR TITLE
Update to Admin SDK

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
Fixes #4 
Fixes #6

**Comment by samtstern** [comment]
@jwngr or @mikelehen PTAL

**Comment by mikelehen** [comment]
@jwngr would know better, but this looks like what I expected!

**Comment by jwngr** [comment]
LGTM. But can you also update the docs to mention "Admin SDK" instead of "Server SDK" and change relevant links from `/docs/server` to `/docs/admin`?

**Comment by samtstern** [comment]
@jwngr done

**Pull request merged**
