### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by ytianhui**
Add SLF4J-based logging, solve the following error:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### CODE REVIEW

**Comment by ytianhui** [comment]
I signed it!

**Comment by samtstern** [comment]
@ytianhui I don't see any references to `slf4j` in our codebase, can you explain a little more about when this error occurs?

**Comment by ytianhui** [comment]
@samtstern 
Thank you for the reply^^/

Due to the following document, Sundial require Dependencies "org.slf4j.slf4j-api-1.7.25".
https://github.com/timmolter/Sundial
In my test, 
adding `compile 'org.slf4j:slf4j-api:1.7.25'` still got same error,
but adding `compile 'org.slf4j:slf4j-simple:1.7.25'`, no SLF4J errors were shown.

**Comment by samtstern** [comment]
Apologies I never responded here but I still cannot see the connection between this repository and Sundial....

**Comment by samtstern** [comment]
This is a very old PR, going to close it since nobody else has mentioned this particular issue.  Thank you for the contribution though!

**Pull request closed without merging**
